### ISSUE TITLE
Auto config file loading appears to include the config file inside /examples

### ISSUE THREAD

**Issue by brandonscript** [brandonscript/usergrid-nodejs#7]
For example:

`Using config file '/Users/xxxx/dev/node_modules/usergrid/examples/api-proxy/config/usergrid.json'`

**Comment by brandonscript** [comment]
Not yet. Been stuck working on other stuff! Happy to accept a PR if you want, otherwise I'll get to it when I can 😉

**Comment by YasharF** [comment]
I think the issue is that this whole walkSync at https://github.com/brandonscript/usergrid-nodejs/blob/master/helpers/config.js#L34 is not needed.

The easy solution is just to say, the config file needs to be  [projectRoot]/config/config.json , hard code it, document it and call the day.

**Comment by brandonscript** [comment]
May definitely go with that, but want to ensure I'm not crippling any existing architecture by doing so.

**Comment by YasharF** [comment]
I am working on a PR.

**Comment by brandonscript** [comment]
One of the factors to consider is the location of the SDK inside `node_modules`; hard coding can be messy with a relative path of someone doesn't default to that dir. This is why walking the folder structure is more robust and flexible.

**Comment by YasharF** [comment]
OK, so two ways I can think of to fix this fairly quick.  (Right now to me it looks like that the usergrid module is broken as the example config is always overwriting app defined usergrid configs):

1. Get rid of the crawling but keep some of the other formatting adjustment that is in there like what I have here https://github.com/YasharF/usergrid-nodejs/commit/aa542ff8b9b69b0574586c6e0cad5b963e178093
2. Keep the crawling as is, rename the example config to something other than usergrid.json or config.json, aka usergrid.example.json and document that if you are trying to run the example, you need to rename the json file.

I have tested both of these with a simple app that I have and they work.

Thoughts?

**Comment by YasharF** [comment]
I created a pull request for each option, so if you are deciding to go with one, you can go with it, and I'll close the other:

1. Get rid of the crawling but keep some of the other formatting adjustment that is in there: https://github.com/brandonscript/usergrid-nodejs/pull/13
2. Changing the name for config file of the example: https://github.com/brandonscript/usergrid-nodejs/pull/12
